# Generated by Django 5.2.6 on 2025-09-22 22:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('performance_link', models.URLField(blank=True, null=True)),
                ('drummers', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('guitarists', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bassists', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vocalists', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('leader_name', models.CharField(max_length=120)),
                ('leader_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('leader_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional +).', regex='^\\+?\\d{7,15}$')])),
                ('leader_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(default=2025)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional +).', regex='^\\+?\\d{7,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('Drummer', 'Drummer'), ('Guitarist', 'Guitarist'), ('Bassist', 'Bassist'), ('Vocalist', 'Vocalist'), ('Other', 'Other')], default='Other', max_length=20)),
                ('is_leader', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bands.team')),
            ],
        ),
    ]
