# Generated by Django 5.2.6 on 2025-09-23 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
